### ISSUE TITLE
Spinner always spin

### ISSUE THREAD

**Issue by cotiga** [m1ge0/bootsjet#1]
Hi, I'm trying your package, it seems to work well. Good job, thanks.

But, I wanted to know if it's normal the spinner always spin?

For example here : resources/views/profile/update-profile-information-form.blade.php

```
<x-button>
    <div wire:loading class="spinner-border spinner-border-sm" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    {{ __('Save') }}
</x-button>
```

**Comment by m1ge0** [comment]
Hey, thanks for using this package.
 
I'm on the go and will look tomorrow into it ✌🏼

**Comment by cotiga** [comment]
Sorry,
After putting the assets in prod and restarting my test machine, operation is now correct. the spinner only spins during recording action. Great!
Thanks again

**Comment by cotiga** [comment]
Rebuild assets make's OK
