### ISSUE TITLE
illuminate/support v11 support

### ISSUE THREAD

**Issue by BenceSzalai** [m1ge0/bootsjet#4]
Hi!
Just tried it on a fresh Laravel project, but it comes with `illuminate/support v11`, so this package cannot be installed.

```log
 m1ge0/bootsjet[1.0, ..., 1.0.3] require illuminate/support ^10.0 -> found illuminate/support[v10.0.0, ..., v10.48.10] but these were not loaded, likely because it conflicts with another require.
```

UPDATE: Nevermind, I can see now there's more to it. There are adjustments that need to be done to stubs. Some files are moved, some are renamed. Also in my project Fortify is not explicitly referenced. So I've got it working manually, but I cannot provide a PR as there are features, like 2FA and Teams that are missing from my project, so I don't know what to do with those files/ lines. I've removed them from my manual "installation" but that's not good enough for a PR.

**Comment by m1ge0** [comment]
Hey @BenceSzalai , just updated the requirements so it should work with laravel 11 and jetstream 5. 

To use it use `composer require m1ge0/bootsjet:2.0-alpha` or update your composer.json... 

Happy coding ✌🏼
